### ISSUE TITLE
No image virtual size specified for box on openFyde

### ISSUE THREAD

**Issue by DarkevilPT** [jbowdre/vagrant-saltlab#2]
https://runtimeterror.dev/create-vms-chromebook-hashicorp-vagrant/
https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1794
![image](https://github.com/jbowdre/vagrant-saltlab/assets/3583885/f50fa0d3-0c87-4656-933c-32a417ca5b4d)
![image](https://github.com/jbowdre/vagrant-saltlab/assets/3583885/5a076481-7eab-4c03-a427-556ab776ea0f)

Hey John I've found your guide and I was trying to replicate it on my openFyde Single Board ARM64 device (using off course alpine for arm64 libvrt) I am always faced with that issue.. idk how to solve it.. maybe vagrand didnt installed properly and Idk if you know anything to point me into the right direction.

Ive also shared your guide at the fyde Forums to see if more people could participate and improve it.
https://community.fydeos.io/t/topic/26953/1

Hope you're ok with that if anything let me know.

**Comment by vimwtf** [comment]
Hi @DarkevilPT,

Hmm, I'm not sure what might be causing that. You are using a different box on a different OS with a different architecture, though, so there are a lot of variables in play beyond what I was working with in my environment. 

Have you tried definining `machine_virtual_size` in the Vagrantfile to see if that addresses the `No image virtual size specified for box` error? Perhaps the metadata for the box you're using just doesn't have that set for some reason.

Otherwise... I'm afraid I'm out of ideas though. I'm hardly a Vagrant expert and only have limited experience with it.

Good luck!

**Comment by DarkevilPT** [comment]
Nice ! I havent no once I get home.
Is it just machine_virtual_size = 10GB ? something like that I imagine. Ive Tried a few options but with no luck.
Ill let you know later on.

Thanks in Advance.

**Comment by vimwtf** [comment]
The [doc](https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html) says it should be specified in GB, so I suspect something like this would do the trick:

```
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.machine_virtual_size = 10
  end
end
```

**Comment by DarkevilPT** [comment]
Yeah same bs.. its because.. rockchip kernel is not mainline plus theres a bunch of issues between it and the stable fake version they modified which makes anything arm on a normal pattern not to work here.. I believe.. Best to wait till fydeOS and rockchip to combine a more stable mainline thing. But hey thanks bro. That tip for VMS on ChromeOS is still dope.

![Screenshot 2023-12-30 18 05 16](https://github.com/jbowdre/vagrant-saltlab/assets/3583885/5fafa935-e821-48cb-b832-a0cac0c921f0)
![Screenshot 2023-12-30 18 05 07](https://github.com/jbowdre/vagrant-saltlab/assets/3583885/b972e945-4e82-4725-af99-733b9f3d936e)
